INSERT INTO `biblioteca`.`tb_livro` (`nome`, `genero`, `ano`) VALUES
('A Jornada do Destino', 'Romance', 1997),
('O Segredo dos Ventos', 'Fantasia', 2005),
('Além da Noite', 'Suspense', 2010),
('O Mistério da Cidade Perdida', 'Aventura', 2012),
('O Guardião da Floresta', 'Fantasia', 2014),
('O Último Refúgio', 'Drama', 1999),
('Os Ecos do Passado', 'Mistério', 2007),
('O Labirinto da Mente', 'Ficção Científica', 2018),
('A Ilha das Sombras', 'Terror', 2001),
('O Perfume da Lua', 'Romance', 1995),
('A Esperança de Viver', 'Drama', 2015),
('O Vendedor de Sonhos', 'Drama', 2009),
('Na Estrada das Estrelas', 'Ficção Científica', 2020),
('O Último Beijo', 'Romance', 1998),
('O Caminho da Vitória', 'Aventura', 2006),
('O Corpo da Alma', 'Filosofia', 2013),
('O Rei das Sombras', 'Fantasia', 2008),
('Os Inimigos do Amanhã', 'Ficção Científica', 2011),
('A Revolução dos Anjos', 'Religião', 2017),
('A Dança dos Espíritos', 'Mistério', 2020),
('O Corpo Perdido', 'Suspense', 2016),
('O Príncipe das Estrelas', 'Fantasia', 2014),
('Corações de Fogo', 'Terror', 2002),
('A Última Lição', 'Drama', 1996),
('O Segredo das Montanhas', 'Aventura', 2000),
('O Sonho de Ícarus', 'Ficção Científica', 2015),
('O Último Sacrifício', 'Mistério', 2003),
('A Floresta das Sombras', 'Fantasia', 2004),
('A Viagem do Herói', 'Aventura', 2012),
('O Reflexo da Lua', 'Romance', 1993),
('O Caminho do Guerreiro', 'Aventura', 2016),
('Vingança na Neve', 'Suspense', 2008),
('As Estações da Vida', 'Drama', 2017),
('O Poço das Almas', 'Fantasia', 2019),
('O Coração do Mundo', 'Ficção Científica', 2021),
('A Última Esperança', 'Romance', 2011),
('O Guardião da Aliança', 'Fantasia', 2010),
('O Fim dos Tempos', 'Terror', 2005),
('No Olho do Furacão', 'Aventura', 2002),
('A Porta do Infinito', 'Ficção Científica', 2018),
('Vidas Que Se Cruzam', 'Drama', 2019),
('Corações de Pedra', 'Romance', 2006),
('O Último Mistério', 'Mistério', 2007),
('A Ilha dos Perdidos', 'Aventura', 2001),
('As Lendas do Fogo', 'Fantasia', 2004),
('O Príncipe e o Dragão', 'Fantasia', 2013),
('A Cidade dos Deuses', 'Ficção Científica', 2015),
('Segredos do Passado', 'Mistério', 2009),
('O Sol da Tarde', 'Romance', 2016),
('A Dança da Morte', 'Terror', 2000),
('O Sonho da Águia', 'Fantasia', 2017),
('O Despertar da Esperança', 'Drama', 2002),
('O Caminho do Destino', 'Aventura', 2015),
('As Sombras do Medo', 'Terror', 2011),
('O Último Estágio', 'Ficção Científica', 2016),
('A Cidade das Estrelas', 'Romance', 2019),
('O Enigma das Sombras', 'Mistério', 2020),
('Vingança no Fim do Mundo', 'Aventura', 2014),
('Lágrimas de Fogo', 'Drama', 2013),
('O Mago das Sombras', 'Fantasia', 2012),
('O Último Dragão', 'Fantasia', 2018),
('O Grande Amor', 'Romance', 2011),
('A Descida ao Inferno', 'Terror', 2015),
('Caminhos da Liberdade', 'Aventura', 2014),
('No Limiar da Mente', 'Ficção Científica', 2019),
('A Ilha dos Abandonados', 'Mistério', 2016),
('O Fim da Jornada', 'Drama', 2020),
('O Inverno das Almas', 'Terror', 2008),
('A Fuga do Destino', 'Romance', 2012),
('O Espelho da Alma', 'Filosofia', 2017),
('A Chave do Destino', 'Aventura', 2015),
('Na Trilha das Estrelas', 'Ficção Científica', 2014),
('A Conquista das Sombras', 'Fantasia', 2020),
('Caminhos da Vitória', 'Drama', 2018),
('O Último Exército', 'Fantasia', 2019),
('O Medo no Olhar', 'Terror', 2013),
('A Jornada de um Herói', 'Aventura', 2009),
('Corações Ardentes', 'Romance', 2016),
('O Caminho da Lua', 'Ficção Científica', 2018),
('O Espelho do Universo', 'Mistério', 2015),
('A História de um Amor', 'Romance', 2002),
('O Último Reinado', 'Fantasia', 2014),
('Vingança no Inferno', 'Terror', 2007),
('Os Portões do Céu', 'Religião', 2011),
('A Magia do Tempo', 'Ficção Científica', 2019),
('O Reino das Sombras', 'Fantasia', 2020),
('O Silêncio do Vento', 'Drama', 2018),
('A Aventura do Rei', 'Aventura', 2011),
('O Guardião do Fogo', 'Fantasia', 2005),
('O Príncipe das Sombras', 'Terror', 2016);
